<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>DanM.GlslOptimizer</PackageId>
    <AssemblyName>DanM.GlslOptimizer</AssemblyName>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <Authors>Dan-Matei Mitreanu</Authors>
    <RepositoryUrl>https://github.com/danmitreanu/glsl-optimizer-sharp</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <Description>
      Managed .NET wrapper around https://github.com/aras-p/glsl-optimizer.
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../bin/**/*"
      Pack="true"
      PackagePath="runtimes/%(RecursiveDir)native/%(Filename)%(Extension)"
      CopyToOutputDirectory="Never"
      Visible="false" />
  </ItemGroup>

</Project>
